### ISSUE TITLE
ITRDB_FUNCTIONS.R line 217 [ read.crn() ]

### ISSUE THREAD

**Issue by bocinsky** [bocinsky/FedData#15]
line 217- seems different from rest of the file. I could see an argument for having these related functions in a separate file (but could also make sense to keep in this file too).

In the best of all possible worlds, the dplR package (from which this function was adapted) would be developed on github or somewhere else where I could suggest a patch. At the moment this is not the case, but eventually I'll hopefully not even have to have this function in the package.

**Comment by bocinsky** [comment]
Left in place... it should remain here, but in future might remove if dplR is improved.

**Comment by BMYusuf** [comment]
A 15 years old boy is watching Bangladesh cricket match on tv.the boys name Hasibul and jersey number 75 is written on the jersey

**Comment by BMYusuf** [comment]
12

**Comment by BMYusuf** [comment]
17
