### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by bocinsky** [bocinsky/FedData#2]
Test on Fedora/Ubuntu/other.

**Comment by benmarwick** [comment]
Travis-CI helps with Ubuntu, and Docker can for other OSs too (there's circle-ci for testing Dockerfiles)

**Comment by bocinsky** [comment]
Ah, yes, good point... My build is still failing though. Adding it as an issue, just to keep it in my list.

**Comment by benmarwick** [comment]
I'm getting something related to `rgdal`: https://travis-ci.org/benmarwick/FedData I made a mock package to explore this (https://travis-ci.org/benmarwick/usergdalwithtravis) which gives the same `configure: error: gdal-config not found or not executable.` error but passes the package tests (ie. from `testthat`) and also Travis-CI. So it's a bit of a puzzle.

**Comment by bocinsky** [comment]
Yeah, Linux or Travis-CI forces rgdal to build from source, and thus to search for GDAL on the system (as opposed to using a prepackaged version of GDAL included in binary distributions of rgdal). I'll try adding "sudo apt-get gdal" somewhere in the Travis-CI header.

KB

**Comment by bocinsky** [comment]
Alright, I have this working now, other than an error in the CRAN build about those non-cran packages.

**Comment by bocinsky** [comment]
Travis now doing build tests... passing currently, and being shown on GitHub repo.
