### ISSUE TITLE
get_nhd returns null list

### ISSUE THREAD

**Issue by trexmiller** [bocinsky/FedData#23]
Running the examples, I get a null list when running get_nhd

> NHD <- get_nhd(template=county, 
+   label=paste(county$STATE,'_',county$NAME, sep=''))
(Down)Loading the NHD HUC4 dataset.
Downloading file (if necessary): ftp://ftp.igsb.uiowa.edu/gis_library/USA/huc_04.zip
(Down)Loading the NHD subregion data.
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM0208_931v220.zip
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM0505_931v220.zip
Merging all NHD data in study area.
> NHD
named list()

**Comment by bocinsky** [comment]
Hi there. Are you running the latest version of FedData? Examples are now done using a different polygon, which suggests to me that you're running an older version, which did at one time have a bug in the get_nhd() function. Please let me know more about the issue you are having.

**Comment by trexmiller** [comment]
Okay, I downloaded FedData_2.0.7.tar.gz from Cran and installed the package from source. I also upgraded R to 3.2.3. Still get a null list with get_nhd. The script I ran is below followed by console window results.

#All of this works
vepPolygon <- polygon_from_extent(raster::extent(672800,740000,4102000,4170000),
                                  proj4string="+proj=utm +datum=NAD83 +zone=12")
NED <- get_ned(template=vepPolygon,
               label="VEPIIN")
plot(NED)
GHCN.prcp <- get_ghcn_daily(template=vepPolygon, 
                            label="VEPIIN",
                            elements=c('prcp'))
plot(GHCN.prcp$spatial, pch=1, add=T)
legend('bottomleft', pch=1, legend="GHCN Precipitation Records")
GHCN.temp <- get_ghcn_daily(template=vepPolygon, 
                            label="VEPIIN", 
                            elements=c('tmin','tmax'), 
                            standardize=T)
plot(NED)
# Plot the spatial locations
plot(GHCN.temp$spatial, add=T, pch=1)
legend('bottomleft', pch=1, legend="GHCN Temperature Records")

#This works, downloads and merges with no errors
NHD <- get_nhd(template=vepPolygon, 
               label="VEPIIN")



# Plot the NED again
raster::plot(NED)
# This does not work. Nothing is added to the plot
plot(NHD$NHDFlowline, add=T)

#Result
> plot(NHD$NHDFlowline, add=T)
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
5: In plot.window(...) : "add" is not a graphical parameter
 


Console window results:

> NHD <- get_nhd(template=vepPolygon, 
+                label="VEPIIN")
(Down)Loading the NHD HUC4 dataset.
Downloading file (if necessary): ftp://ftp.igsb.uiowa.edu/gis_library/USA/huc_04.zip
(Down)Loading the NHD subregion data.
Downloading file: ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1403_931v220.zip
Downloading file: ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1408_931v220.zip
Merging all NHD data in study area.
> plot(NED)
> plot(NHD$NHDFlowline, add=T)
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
5: In plot.window(...) : "add" is not a graphical parameter
> NHD$NHDFlowline
NULL
> NHD
named list()

**Comment by bocinsky** [comment]
Hi again.

I’m having trouble reproducing the error… it’s working for me every time. Would you try adding force.redo = T to the get_nhd function call? This will overwrite whatever NHD data you have already downloaded for the VEPIIN label. Alternatively you can change the label.

e.g., 

NHD <- get_nhd(template=vepPolygon, 
               label="VEPIIN",
               force.redo = T)

**Comment by trexmiller** [comment]
Strange, still doesn’t work for me. I added force.redo=T and also tried changing the label (see below). 

> NHD <- get_nhd(template=vepPolygon,label="VEPIIN",force.redo = T)
(Down)Loading the NHD HUC4 dataset.
Downloading file (if necessary): ftp://ftp.igsb.uiowa.edu/gis_library/USA/huc_04.zip
(Down)Loading the NHD subregion data.
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1403_931v220.zip
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1408_931v220.zip
Merging all NHD data in study area.
> NHD
named list()
> NHD <- get_nhd(template=vepPolygon,label="VEPIIN2",force.redo = T)
(Down)Loading the NHD HUC4 dataset.
Downloading file (if necessary): ftp://ftp.igsb.uiowa.edu/gis_library/USA/huc_04.zip
(Down)Loading the NHD subregion data.
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1403_931v220.zip
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1408_931v220.zip
Merging all NHD data in study area.
> NHD
named list()


I have taken the get_nhd function and run each command individually and found that the subregionShapes step below is where I get the null list. Previous steps seem to work fine.

 HUC4 <- get_huc4(template = template, raw.dir = raw.dir)
Downloading file (if necessary): ftp://ftp.igsb.uiowa.edu/gis_library/USA/huc_04.zip
>  HUC4
class       : SpatialPolygonsDataFrame 
features    : 2 
extent      : -932781.4, -851919, 4209915, 4291423  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=15 +datum=NAD83 +ellps=WGS84 +towgs84=0,0,0 
variables   : 6
names       : HUC4, COUNT,               SUB_NAME, HUC2,              REG_NAME,    ACRES 
min values  : 1403,     5,               San Juan,   14, Upper Colorado Region,  5561890 
max values  : 1408,    12, Upper Colorado-Dolores,   14, Upper Colorado Region, 16676970 
> area.list <- formatC(HUC4$HUC4, width = 4, format = "d", 
+         flag = "0")
> area.list
[1] "1403" "1408"

> subregionShapes <- lapply(area.list, function(area) {
+         return(get_nhd_subregion(template = template, area = area, 
+             res = res, raw.dir = raw.dir))
+     })
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1403_931v220.zip
Downloading file (if necessary): ftp://nhdftp.usgs.gov/DataSets/Staged/SubRegions/FileGDB/MediumResolution/NHDM1408_931v220.zip
> subregionShapes
[[1]]
named list()

[[2]]
named list()

Still looking, but assuming the problem is with get_nhd_subregion (maybe?)

**Comment by trexmiller** [comment]
This part in get_nhd_subregion gives me null shapes list


> shapes <- lapply(layers, function(layer) {
+         tryCatch(suppressWarnings(rgdal::readOGR(dsn = dsn, layer = layer, 
+             verbose = F)), error = function(e) NULL)
+     })
> shapes
[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

[[8]]
NULL

[[9]]
NULL

[[10]]
NULL

[[11]]
NULL

**Comment by bocinsky** [comment]
Can you provide me the output of sessionInfo()?

**Comment by bocinsky** [comment]
(after the failure)

**Comment by trexmiller** [comment]
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgeos_0.3-11        FedData_2.0.7       hydroMap_0.0.0      dataRetrieval_2.5.2
[5] rgdal_1.0-4         sp_1.1-1           

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      raster_2.4-18    magrittr_1.5     lattice_0.20-33  R6_2.1.2        
 [6] stringr_1.0.0    httr_1.1.0       plyr_1.8.3       dplyr_0.4.3      tools_3.2.3     
[11] parallel_3.2.3   grid_3.2.3       data.table_1.9.6 DBI_0.3.1        assertthat_0.1  
[16] readr_0.2.2      reshape2_1.4.1   curl_0.9.6       stringi_1.0-1    XML_3.98-1.4    
[21] lubridate_1.5.0  chron_2.3-47

**Comment by trexmiller** [comment]
Okay, that might be it, but I’m having trouble installing the latest source of rgdal, rgdal_1.1-3.tar.gz

* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
configure: rgdal: 1.1-3
checking for /usr/bin/svnversion... yes
configure: svn revision: 594
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rgdal’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rgdal’
> 

Strange because I have GDAL installed and have changed my path variable.

**Comment by trexmiller** [comment]
After upgrading to the latest version of R and installing latest version of FedData package and all dependencies it works for me, but only in Windows, which is fine for now. Thanks for your help! This will be very useful to my lab’s research. 

Wonder if you could point me to a resource for deciphering coordinates of the extent argument. I don’t know how to change the extent coordinates in polygon_from_extent to get the area we are interested in.

**Comment by bocinsky** [comment]
Sweet! I’ll add something to the package DESCRIPTION file that stipulates that the version of rgdal must be >= 1.1 

Look up the help file for the raster::extent() function; you can create any rectangular extent just using the minimum and maximum x (longitude) and y (latitude) values.

Best,
Kyle
