### ISSUE TITLE
Hydrography data moved

### ISSUE THREAD

**Issue by StabEmInDaFace** [bocinsky/FedData#24]
The USGS moved the hydrography ftp, the address the used in get_nhd() returns an error.
The new ftp, according to the site, is:
ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Hydrography/

**Comment by bocinsky** [comment]
Thanks. Looking into it now. They seem to have stopped offering the "medium" resolution NHD subregions as well, so switching to all "high" resolution.

**Comment by bocinsky** [comment]
Testing worked. Just pushed changes, and submitted 2.0.10 to CRAN. Thanks again!
