### ISSUE TITLE
get_daymet from polygon template

### ISSUE THREAD

**Issue by jsocolar** [bocinsky/FedData#29]
Hey Kyle,
One more: when using get_daymet with a polygon template, everything works great if the template only covers one daymet tile.  But otherwise, I encounter a problem (for example if the template is the California polygon embedded in [this shapefile](https://www.arcgis.com/home/item.html?id=f7f805eb65eb4ab787a0a3e1116ca7e5)).  It seems to come from two places.  At line 95, I think that sp::over doesn't have a method for x = "SpatialPolygonsDataFrame", y = "SpatialPolygons".  I just get a single Daymet tile when I run this code (not sure whether there's rhyme or reason to which one I get).  I can fix this by replacing line 95 with
`  tile.ids <- tiles$TileID[rgeos::gIntersects(template.latlon, tiles, byid = T)]`

Second, for me the code fails to run unless I delete line 87, whose purpose is a bit mysterious to me. I'm a bit worried that I'm breaking something by deleting it, but I can't see what might be broken.

I'm now in the middle of a big 22-tile download, and I'll let you know if anything seems amiss once it finishes.

**Edited to add:** bizarrely, get_daymet cannot download year 2005 tmax data for tile 11011.  Perhaps an issue on Daymet's side?

**Edit 2:** Now I also get a problem in the mosaicking step, which I solved by just returning `tiles` after line 103 and manipulating it in a fairly kludgy way.  This is probably just a result of my own clumsiness--crashing around and breaking things in your code :)

Cheers
Jacob

**Comment by bocinsky** [comment]
Hey, thanks so much again, Jacob! I very much appreciate your help in squashing these bugs.

Good job spotting the %over% issue... I changed the code in a different (but synonymous) way to your fix (i.e., I still use the %over% function).

I can't seem to figure out the line 87 problem; that section of code allows for cacheing results. If you ran it before (even if it errored out) you could have incidentally cached incorrect or corrupted data. Try running with force.redo=TRUE (which will re-download all the data... beware!) or else delete the "EXTRACTIONS" directory, which will use the currently downloaded data but perform a re-extraction for your study area.

It seems the raster package subtly changed the mosaic function, which now requires naming the first two elements "x" and "y" if mosaicking a list. I've updated, and it should be working now.

Finally, there was an error in the mosaic foreach loop; it wasn't outputting the mosaicked raster at the end. It is now, and should write correctly. I'm going to push to GitHub. Could you try running your code again (you shouldn't have to re-download... just clear the "EXTRACTIONS" directory)? When I hear from you, I'll close this issue and push an update to the CRAN.

**Comment by bocinsky** [comment]
Pushing new version to CRAN.
